#ifndef INCLUDES_H
#define INCLUDES_H

#include "Expression.h"
#include "True.h"
#include "False.h"
#include "BinExpression.h"
#include "Id.h"
#include "Statement.h"
#include "Main.h"
#include "Program.h"
#include "Method.h"
#include "Class.h"
#include "Variable.h"
#include "ClassSeq.h"
#include "MethodSeq.h"
#include "VariableSeq.h"
#include "StatementSeq.h"
#include "IntegerExp.h"
#include "BooleanExp.h"
#include "IdExp.h"
#include "If.h"
#include "AssignStatement.h"
#include "NotExp.h"
#include "ExpSeq.h"
#include "CallMethod.h"
#include "NewIntArray.h"
#include "NewClassObject.h"
#include "RandomAccess.h"
#include "Length.h"
#include "This.h"
#include "PrintLine.h"
#include "While.h"

#endif // INCLUDES_H
