SOURCE=main.cpp AllProblemsSolution.cpp visitors/PrettyPrinter.cpp SymbolTable/table.cpp SymbolTable/SymbolTable.cpp visitors/SymbolTableVisitor.cpp 

all: main

main: main.cpp
	g++ -g $(SOURCE) -o main.o

clean:
	rm main.o
