#include "Visitor.h"
void IVisitor::visit(const CBinExpression *node){}
void IVisitor::visit(const CId* node){}
void IVisitor::visit(const CTrue *node){}
void IVisitor::visit(const CFalse *node){}
void IVisitor::visit(const CClass* node){}
void IVisitor::visit(const CMain* node){}
void IVisitor::visit(const CMethod* node){}
void IVisitor::visit(const CProgram* node){}
void IVisitor::visit(const CBooleanExp* node){}
void IVisitor::visit(const CIntegerExp* node){}
void IVisitor::visit(const CAssignStatement* node){}
void IVisitor::visit(const CIf* node){}
void IVisitor::visit(const CIdExp* node){}
void IVisitor::visit(const CNotExp* node){}
void IVisitor::visit(const CCallMethod* node){}
void IVisitor::visit(const CNewIntArray* node){}
void IVisitor::visit(const CNewClassObject* node){}
void IVisitor::visit(const CRandomAccess* node){}
void IVisitor::visit(const CLength* node){}
void IVisitor::visit(const CPrintLine* node){}
void IVisitor::visit(const CWhile* node){}
