#include "Visitor.h"
void IVisitor::visit(CBinExpression* node){}
void IVisitor::visit(CId* node){}
void IVisitor::visit(CTrue* node){}
void IVisitor::visit(CFalse* node){}
void IVisitor::visit(CClass* node){}
void IVisitor::visit(CMain* node){}
void IVisitor::visit(CMethod* node){}
void IVisitor::visit(CProgram* node){}
void IVisitor::visit(CBooleanExp* node){}
void IVisitor::visit(CIntegerExp* node){}
void IVisitor::visit(CAssignStatement* node){}
void IVisitor::visit(CIf* node){}
void IVisitor::visit(CIdExp* node){}
void IVisitor::visit(CNotExp* node){}
void IVisitor::visit(CCallMethod* node){}
void IVisitor::visit(CNewIntArray* node){}
void IVisitor::visit(CNewClassObject* node){}
void IVisitor::visit(CRandomAccess* node){}
void IVisitor::visit(CLength* node){}
void IVisitor::visit(CPrintLine* node){}
void IVisitor::visit(CWhile* node){}
